version: "3.8"
services:
  backend:
    image: "denizerbay/spring-react-fullstack:25.7.2022.20.58.58"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev